/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesNewRouteImport } from './routes/repositories/new'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RepoOwnerNameIndexRouteImport } from './routes/repo.$owner.$name.index'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepositoriesRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameIndexRoute = RepoOwnerNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRouteWithChildren
  '/repo/$owner/$name/': typeof RepoOwnerNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRouteWithChildren
  '/repo/$owner/$name/': typeof RepoOwnerNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name'
    | '/repo/$owner/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name'
    | '/repo/$owner/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name/': {
      id: '/repo/$owner/$name/'
      path: '/'
      fullPath: '/repo/$owner/$name/'
      preLoaderRoute: typeof RepoOwnerNameIndexRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesNewRoute: typeof RepositoriesNewRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesNewRoute: RepositoriesNewRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface RepoOwnerNameRouteChildren {
  RepoOwnerNameIndexRoute: typeof RepoOwnerNameIndexRoute
}

const RepoOwnerNameRouteChildren: RepoOwnerNameRouteChildren = {
  RepoOwnerNameIndexRoute: RepoOwnerNameIndexRoute,
}

const RepoOwnerNameRouteWithChildren = RepoOwnerNameRoute._addFileChildren(
  RepoOwnerNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RepoOwnerNameRoute: RepoOwnerNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
