/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesNewRouteImport } from './routes/repositories/new'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as RepoOwnerNameIndexRouteImport } from './routes/repo.$owner.$name.index'
import { Route as RepoOwnerNameUploadRouteImport } from './routes/repo/$owner.$name.upload'
import { Route as RepoOwnerNamePullsRouteImport } from './routes/repo/$owner.$name.pulls'
import { Route as RepoOwnerNameIssuesRouteImport } from './routes/repo/$owner.$name.issues'
import { Route as RepoOwnerNameCommitsRouteImport } from './routes/repo/$owner.$name.commits'
import { Route as RepoOwnerNamePullsIdRouteImport } from './routes/repo/$owner.$name.pulls.$id'
import { Route as RepoOwnerNameIssuesIdRouteImport } from './routes/repo/$owner.$name.issues.$id'
import { Route as RepoOwnerNameCommitShaRouteImport } from './routes/repo/$owner.$name.commit.$sha'
import { Route as RepoOwnerNameBlobBranchSplatRouteImport } from './routes/repo/$owner.$name.blob.$branch.$'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesNewRoute = RepositoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RepositoriesRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameIndexRoute = RepoOwnerNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNameUploadRoute = RepoOwnerNameUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNamePullsRoute = RepoOwnerNamePullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNameIssuesRoute = RepoOwnerNameIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNameCommitsRoute = RepoOwnerNameCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNamePullsIdRoute = RepoOwnerNamePullsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepoOwnerNamePullsRoute,
} as any)
const RepoOwnerNameIssuesIdRoute = RepoOwnerNameIssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepoOwnerNameIssuesRoute,
} as any)
const RepoOwnerNameCommitShaRoute = RepoOwnerNameCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => RepoOwnerNameRoute,
} as any)
const RepoOwnerNameBlobBranchSplatRoute =
  RepoOwnerNameBlobBranchSplatRouteImport.update({
    id: '/blob/$branch/$',
    path: '/blob/$branch/$',
    getParentRoute: () => RepoOwnerNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRouteWithChildren
  '/repo/$owner/$name/commits': typeof RepoOwnerNameCommitsRoute
  '/repo/$owner/$name/issues': typeof RepoOwnerNameIssuesRouteWithChildren
  '/repo/$owner/$name/pulls': typeof RepoOwnerNamePullsRouteWithChildren
  '/repo/$owner/$name/upload': typeof RepoOwnerNameUploadRoute
  '/repo/$owner/$name/': typeof RepoOwnerNameIndexRoute
  '/repo/$owner/$name/commit/$sha': typeof RepoOwnerNameCommitShaRoute
  '/repo/$owner/$name/issues/$id': typeof RepoOwnerNameIssuesIdRoute
  '/repo/$owner/$name/pulls/$id': typeof RepoOwnerNamePullsIdRoute
  '/repo/$owner/$name/blob/$branch/$': typeof RepoOwnerNameBlobBranchSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name/commits': typeof RepoOwnerNameCommitsRoute
  '/repo/$owner/$name/issues': typeof RepoOwnerNameIssuesRouteWithChildren
  '/repo/$owner/$name/pulls': typeof RepoOwnerNamePullsRouteWithChildren
  '/repo/$owner/$name/upload': typeof RepoOwnerNameUploadRoute
  '/repo/$owner/$name': typeof RepoOwnerNameIndexRoute
  '/repo/$owner/$name/commit/$sha': typeof RepoOwnerNameCommitShaRoute
  '/repo/$owner/$name/issues/$id': typeof RepoOwnerNameIssuesIdRoute
  '/repo/$owner/$name/pulls/$id': typeof RepoOwnerNamePullsIdRoute
  '/repo/$owner/$name/blob/$branch/$': typeof RepoOwnerNameBlobBranchSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/repositories/new': typeof RepositoriesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRouteWithChildren
  '/repo/$owner/$name/commits': typeof RepoOwnerNameCommitsRoute
  '/repo/$owner/$name/issues': typeof RepoOwnerNameIssuesRouteWithChildren
  '/repo/$owner/$name/pulls': typeof RepoOwnerNamePullsRouteWithChildren
  '/repo/$owner/$name/upload': typeof RepoOwnerNameUploadRoute
  '/repo/$owner/$name/': typeof RepoOwnerNameIndexRoute
  '/repo/$owner/$name/commit/$sha': typeof RepoOwnerNameCommitShaRoute
  '/repo/$owner/$name/issues/$id': typeof RepoOwnerNameIssuesIdRoute
  '/repo/$owner/$name/pulls/$id': typeof RepoOwnerNamePullsIdRoute
  '/repo/$owner/$name/blob/$branch/$': typeof RepoOwnerNameBlobBranchSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name'
    | '/repo/$owner/$name/commits'
    | '/repo/$owner/$name/issues'
    | '/repo/$owner/$name/pulls'
    | '/repo/$owner/$name/upload'
    | '/repo/$owner/$name/'
    | '/repo/$owner/$name/commit/$sha'
    | '/repo/$owner/$name/issues/$id'
    | '/repo/$owner/$name/pulls/$id'
    | '/repo/$owner/$name/blob/$branch/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name/commits'
    | '/repo/$owner/$name/issues'
    | '/repo/$owner/$name/pulls'
    | '/repo/$owner/$name/upload'
    | '/repo/$owner/$name'
    | '/repo/$owner/$name/commit/$sha'
    | '/repo/$owner/$name/issues/$id'
    | '/repo/$owner/$name/pulls/$id'
    | '/repo/$owner/$name/blob/$branch/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/repositories'
    | '/auth/login'
    | '/auth/register'
    | '/repositories/new'
    | '/api/auth/$'
    | '/repo/$owner/$name'
    | '/repo/$owner/$name/commits'
    | '/repo/$owner/$name/issues'
    | '/repo/$owner/$name/pulls'
    | '/repo/$owner/$name/upload'
    | '/repo/$owner/$name/'
    | '/repo/$owner/$name/commit/$sha'
    | '/repo/$owner/$name/issues/$id'
    | '/repo/$owner/$name/pulls/$id'
    | '/repo/$owner/$name/blob/$branch/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/new': {
      id: '/repositories/new'
      path: '/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof RepositoriesNewRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name/': {
      id: '/repo/$owner/$name/'
      path: '/'
      fullPath: '/repo/$owner/$name/'
      preLoaderRoute: typeof RepoOwnerNameIndexRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/upload': {
      id: '/repo/$owner/$name/upload'
      path: '/upload'
      fullPath: '/repo/$owner/$name/upload'
      preLoaderRoute: typeof RepoOwnerNameUploadRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/pulls': {
      id: '/repo/$owner/$name/pulls'
      path: '/pulls'
      fullPath: '/repo/$owner/$name/pulls'
      preLoaderRoute: typeof RepoOwnerNamePullsRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/issues': {
      id: '/repo/$owner/$name/issues'
      path: '/issues'
      fullPath: '/repo/$owner/$name/issues'
      preLoaderRoute: typeof RepoOwnerNameIssuesRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/commits': {
      id: '/repo/$owner/$name/commits'
      path: '/commits'
      fullPath: '/repo/$owner/$name/commits'
      preLoaderRoute: typeof RepoOwnerNameCommitsRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/pulls/$id': {
      id: '/repo/$owner/$name/pulls/$id'
      path: '/$id'
      fullPath: '/repo/$owner/$name/pulls/$id'
      preLoaderRoute: typeof RepoOwnerNamePullsIdRouteImport
      parentRoute: typeof RepoOwnerNamePullsRoute
    }
    '/repo/$owner/$name/issues/$id': {
      id: '/repo/$owner/$name/issues/$id'
      path: '/$id'
      fullPath: '/repo/$owner/$name/issues/$id'
      preLoaderRoute: typeof RepoOwnerNameIssuesIdRouteImport
      parentRoute: typeof RepoOwnerNameIssuesRoute
    }
    '/repo/$owner/$name/commit/$sha': {
      id: '/repo/$owner/$name/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/repo/$owner/$name/commit/$sha'
      preLoaderRoute: typeof RepoOwnerNameCommitShaRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
    '/repo/$owner/$name/blob/$branch/$': {
      id: '/repo/$owner/$name/blob/$branch/$'
      path: '/blob/$branch/$'
      fullPath: '/repo/$owner/$name/blob/$branch/$'
      preLoaderRoute: typeof RepoOwnerNameBlobBranchSplatRouteImport
      parentRoute: typeof RepoOwnerNameRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesNewRoute: typeof RepositoriesNewRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesNewRoute: RepositoriesNewRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface RepoOwnerNameIssuesRouteChildren {
  RepoOwnerNameIssuesIdRoute: typeof RepoOwnerNameIssuesIdRoute
}

const RepoOwnerNameIssuesRouteChildren: RepoOwnerNameIssuesRouteChildren = {
  RepoOwnerNameIssuesIdRoute: RepoOwnerNameIssuesIdRoute,
}

const RepoOwnerNameIssuesRouteWithChildren =
  RepoOwnerNameIssuesRoute._addFileChildren(RepoOwnerNameIssuesRouteChildren)

interface RepoOwnerNamePullsRouteChildren {
  RepoOwnerNamePullsIdRoute: typeof RepoOwnerNamePullsIdRoute
}

const RepoOwnerNamePullsRouteChildren: RepoOwnerNamePullsRouteChildren = {
  RepoOwnerNamePullsIdRoute: RepoOwnerNamePullsIdRoute,
}

const RepoOwnerNamePullsRouteWithChildren =
  RepoOwnerNamePullsRoute._addFileChildren(RepoOwnerNamePullsRouteChildren)

interface RepoOwnerNameRouteChildren {
  RepoOwnerNameCommitsRoute: typeof RepoOwnerNameCommitsRoute
  RepoOwnerNameIssuesRoute: typeof RepoOwnerNameIssuesRouteWithChildren
  RepoOwnerNamePullsRoute: typeof RepoOwnerNamePullsRouteWithChildren
  RepoOwnerNameUploadRoute: typeof RepoOwnerNameUploadRoute
  RepoOwnerNameIndexRoute: typeof RepoOwnerNameIndexRoute
  RepoOwnerNameCommitShaRoute: typeof RepoOwnerNameCommitShaRoute
  RepoOwnerNameBlobBranchSplatRoute: typeof RepoOwnerNameBlobBranchSplatRoute
}

const RepoOwnerNameRouteChildren: RepoOwnerNameRouteChildren = {
  RepoOwnerNameCommitsRoute: RepoOwnerNameCommitsRoute,
  RepoOwnerNameIssuesRoute: RepoOwnerNameIssuesRouteWithChildren,
  RepoOwnerNamePullsRoute: RepoOwnerNamePullsRouteWithChildren,
  RepoOwnerNameUploadRoute: RepoOwnerNameUploadRoute,
  RepoOwnerNameIndexRoute: RepoOwnerNameIndexRoute,
  RepoOwnerNameCommitShaRoute: RepoOwnerNameCommitShaRoute,
  RepoOwnerNameBlobBranchSplatRoute: RepoOwnerNameBlobBranchSplatRoute,
}

const RepoOwnerNameRouteWithChildren = RepoOwnerNameRoute._addFileChildren(
  RepoOwnerNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RepoOwnerNameRoute: RepoOwnerNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
